# Generated by Django 4.0.2 on 2022-03-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
